wandb_version: 1

model:
  desc: null
  value: cvae
dataset:
  desc: null
  value: d+e+r+m+a+m+n+i+s+t
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720965604
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
