wandb_version: 1

model:
  desc: null
  value: vanilla_vae
dataset:
  desc: null
  value: pathmnist
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719500392.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
